FROM docker.io/library/python:3.11-slim-bookworm

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY src src

CMD ["/usr/local/bin/python3" ,"/app/src/main.py"]
