apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: hogwarts
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        name: teachers-lounge
  - role: worker
    labels:
      type: house
      house: slytherin
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        name: slytherin
        taints:
          - key: house
            value: slytherin
            effect: NoSchedule
  - role: worker
    labels:
      type: house
      house: hufflepuff
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        name: hufflepuff
        taints:
          - key: house
            value: hufflepuff
            effect: NoSchedule
  - role: worker
    labels:
      type: house
      house: ravenclaw
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        name: ravenclaw
        taints:
          - key: house
            value: ravenclaw
            effect: NoSchedule
  - role: worker
    labels:
      type: house
      house: gryffindor
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        name: gryffindor
        taints:
          - key: house
            value: gryffindor
            effect: NoSchedule
